# Generated by Django 5.1.5 on 2025-03-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('credit', models.FloatField(default=0.0)),
                ('debit', models.FloatField(default=0.0)),
                ('running_balance', models.FloatField(default=0.0)),
            ],
        ),
    ]
